<?php
// Combined Migrations - generated by script
// NOTE: include paths adjusted to reference project includes from this file's directory

// --- Begin migration.php ---

$host = 'localhost';
$db   = 'bhs_clone';
$user = 'root';
$pass = 'mysql';
$charset = 'utf8mb4';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=$charset", $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
    $pdo->exec("ALTER TABLE users ADD COLUMN verification_code VARCHAR(10) NULL DEFAULT NULL, ADD COLUMN verification_expires DATETIME NULL DEFAULT NULL;");
    echo "Success\n";
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}

// --- End migration.php ---


// --- Begin migration_blog_category.php ---

require_once __DIR__ . '/../includes/database.php';

try {
    $db = db();
    $db->exec("ALTER TABLE `blog_posts` ADD COLUMN `category` VARCHAR(50) DEFAULT 'General' AFTER `slug`;");
    echo "Column category added successfully.\n";
} catch (PDOException $e) {
    if (strpos($e->getMessage(), 'Duplicate column name') !== false) {
        echo "Column category already exists.\n";
    } else {
        echo "Error: " . $e->getMessage() . "\n";
    }
}

// --- End migration_blog_category.php ---


// --- Begin migration_enterprise.php ---

require_once __DIR__ . '/../includes/database.php';

try {
    $db = db();
    
    // 1. Saved Properties
    $db->exec("CREATE TABLE IF NOT EXISTS `saved_properties` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `user_id` INT NOT NULL,
        `property_id` INT NOT NULL,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY `unique_save` (`user_id`, `property_id`),
        FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
        FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB;");
    echo "Table 'saved_properties' created/verified.<br>\n";

    // 2. Saved Searches
    $db->exec("CREATE TABLE IF NOT EXISTS `saved_searches` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `user_id` INT NOT NULL,
        `search_name` VARCHAR(100),
        `criteria` JSON NOT NULL,
        `receive_alerts` TINYINT(1) DEFAULT 1,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB;");
    echo "Table 'saved_searches' created/verified.<br>\n";

    // 3. Tour Schedules
    $db->exec("CREATE TABLE IF NOT EXISTS `tour_schedules` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `user_id` INT NOT NULL,
        `property_id` INT NOT NULL,
        `tour_date` DATE NOT NULL,
        `tour_time` TIME NOT NULL,
        `tour_type` ENUM('in-person', 'video') DEFAULT 'in-person',
        `status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
        `message` TEXT,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
        FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB;");
    echo "Table 'tour_schedules' created/verified.<br>\n";

    // 4. Update 'users' table role ENUM to include 'agent'
    // MySQL ALTER TABLE ENUM requires redefining the ENUM
    $db->exec("ALTER TABLE `users` MODIFY COLUMN `role` ENUM('user', 'admin', 'agent') DEFAULT 'user';");
    echo "Table 'users' altered to include 'agent' role.<br>\n";

    echo "<h3>Migration completed successfully!</h3>";

} catch (PDOException $e) {
    echo "Error: " . $e->getMessage() . "<br>\n";
}

// --- End migration_enterprise.php ---


// --- Begin migration_ethiopian_data.php ---

/**
 * Migration: Convert data to Ethiopian Locale
 * Updates names, phone numbers in users, testimonials, and settings.
 */
require_once __DIR__ . '/../includes/database.php';
require_once __DIR__ . '/../includes/config.php';

try {
    // 1. Update Settings
    $stmt = db()->prepare("UPDATE site_settings SET setting_value = ? WHERE setting_key = 'contact_phone'");
    $stmt->execute(['+251 911 234 567']);

    // 2. Update Agents (Users where role = 'user')
    // Let's get existing agents
    $stmt = db()->query("SELECT id FROM users WHERE role = 'user' ORDER BY id ASC");
    $agent_ids = $stmt->fetchAll(PDO::FETCH_COLUMN);

    $ethiopian_agents = [
        ['Abebe Bekele', 'abebe@hawassa.com', '+251 911 234 567', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80'],
        ['Aster Yilma', 'aster@hawassa.com', '+251 912 345 678', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80'],
        ['Dawit Tadesse', 'dawit@hawassa.com', '+251 913 456 789', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80'],
        ['Selamawit Kebede', 'selamawit@hawassa.com', '+251 914 567 890', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80'],
        ['Ephrem Alemu', 'ephrem@hawassa.com', '+251 915 678 901', 'https://images.unsplash.com/photo-1598550874175-4d0ef436c909?auto=format&fit=crop&w=400&q=80'],
    ];

    $update_user = db()->prepare("UPDATE users SET name = ?, phone = ?, avatar = ? WHERE id = ?");
    
    foreach ($agent_ids as $index => $id) {
        $agent = $ethiopian_agents[$index % count($ethiopian_agents)];
        $update_user->execute([$agent[0], $agent[2], $agent[3], $id]);
    }

    // 3. Update Testimonials
    // Let's get existing testimonials
    $stmt = db()->query("SELECT id FROM testimonials ORDER BY id ASC");
    $test_ids = $stmt->fetchAll(PDO::FETCH_COLUMN);

    $ethiopian_testimonials = [
        ['Yonas Haile', 'CEO, EthioTech', 'Hawassa Real Estate provided unparalleled service. The attention to detail and market knowledge helped me secure my dream property.', 5, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80'],
        ['Hirut Worku', 'Investor', 'As a diaspora buyer, I needed someone I could trust. My agent went above and beyond to make the transaction seamless and stress-free.', 5, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80'],
        ['Bereket Mamo', 'Philanthropist', 'The level of discretion and professionalism exhibited by the team was outstanding. Truly the best luxury real estate brokerage in Ethiopia.', 5, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80']
    ];

    $update_test = db()->prepare("UPDATE testimonials SET name = ?, position = ?, content = ? WHERE id = ?");

    foreach ($test_ids as $index => $id) {
        $test = $ethiopian_testimonials[$index % count($ethiopian_testimonials)];
        $update_test->execute([$test[0], $test[1], $test[2], $id]);
    }

    echo "Migration completed successfully: Ethiopian names and phone numbers updated.\n";
} catch (PDOException $e) {
    echo "Migration failed: " . $e->getMessage() . "\n";
}

// --- End migration_ethiopian_data.php ---


// --- Begin migration_new_features.php ---

require_once __DIR__ . '/../includes/database.php';
require_once __DIR__ . '/../includes/config.php';

try {
    $db = db();
    
    // Announcements table
    $db->exec("CREATE TABLE IF NOT EXISTS `announcements` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `title` VARCHAR(255) NOT NULL,
        `content` TEXT,
        `discount_percentage` INT DEFAULT 0,
        `status` ENUM('active','inactive') DEFAULT 'active',
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;");

    // Chat Messages table
    $db->exec("CREATE TABLE IF NOT EXISTS `chat_messages` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `sender_id` INT NULL, /* NULL if anonymous guest, but better to require login or use session ID */
        `session_id` VARCHAR(100) NULL,
        `agent_id` INT NOT NULL,
        `property_id` INT NULL,
        `message` TEXT NOT NULL,
        `is_agent` TINYINT(1) DEFAULT 0,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (`agent_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB;");

    echo "Tables created successfully.\n";

} catch (PDOException $e) {
    echo "Error: " . $e->getMessage() . "\n";
}

// --- End migration_new_features.php ---


// --- Begin migration_property_offers.php ---

require_once __DIR__ . '/../includes/database.php';

try {
    $db = db();
    $db->exec("ALTER TABLE `announcements` ADD COLUMN `property_id` INT NULL DEFAULT NULL AFTER `id`;");
    $db->exec("ALTER TABLE `announcements` ADD FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE SET NULL;");
    echo "Column property_id added successfully.\n";
} catch (PDOException $e) {
    if (strpos($e->getMessage(), 'Duplicate column name') !== false) {
        echo "Column property_id already exists.\n";
    } else {
        echo "Error: " . $e->getMessage() . "\n";
    }
}

// --- End migration_property_offers.php ---


// --- Begin migration_rich_media.php ---

require_once __DIR__ . '/../includes/database.php';

try {
    $db = db();
    
    // Add columns to properties table
    $columns_to_add = [
        'virtual_tour_url' => "VARCHAR(255) DEFAULT NULL",
        'video_url' => "VARCHAR(255) DEFAULT NULL",
        'floor_plan_image' => "VARCHAR(255) DEFAULT NULL"
    ];

    foreach ($columns_to_add as $col_name => $col_def) {
        try {
            $db->exec("ALTER TABLE `properties` ADD COLUMN `$col_name` $col_def;");
            echo "Column '$col_name' added successfully.<br>\n";
        } catch (PDOException $e) {
            // Error 1060 is "Duplicate column name", which means it already exists. We can ignore it safely.
            if ($e->getCode() == '42S21') { 
                echo "Column '$col_name' already exists.<br>\n";
            } else {
                echo "Error adding '$col_name': " . $e->getMessage() . "<br>\n";
            }
        }
    }

    echo "<h3>Migration completed successfully!</h3>";

} catch (PDOException $e) {
    echo "Error: " . $e->getMessage() . "<br>\n";
}

// --- End migration_rich_media.php ---
